// SCHEMA TYPES
export const SCHEMA_CREATE = "SCHEMA_CREATE";
export const SCHEMA_RETRIEVE = "SCHEMA_RETRIEVE";
export const SCHEMA_UPDATE = "SCHEMA_UPDATE";
export const SCHEMA_DELETE = "SCHEMA_DELETE";


// DT(Data types) TYPES
export const DATATYPE_RETRIEVE = "DATATYPE_RETRIEVE";
export const DATATYPE_UPDATE = "DATATYPE_UPDATE";

// DS(Data sets) TYPES

export const DATASET_RETRIEVE = "DATASET_RETRIEVE";
export const DATASET_CREATE = "DATASET_CREATE";
export const PROGRESS_BAR = "PROGRESS_BAR";
export const DATASET_UPDATE = "DATASET_UPDATE"