// SCHEMA TYPES
export const SCHEMA_CREATE = "SCHEMA_CREATE";
export const SCHEMA_RETRIEVE = "SCHEMA_RETRIEVE";
export const SCHEMA_UPDATE = "SCHEMA_UPDATE";
export const SCHEMA_DELETE = "SCHEMA_DELETE";


// DT(Data types) TYPES
export const DATATYPE_RETRIEVE = "DATATYPE_RETRIEVE";
export const DATATYPE_UPDATE = "DATATYPE_UPDATE";

// DS(Data sets) TYPES

export const DATASET_RETRIEVE = "DATASET_RETRIEVE";
export const DATASET_CREATE = "DATASET_CREATE";
export const PROGRESS_BAR = "PROGRESS_BAR";
export const DATASET_UPDATE = "DATASET_UPDATE"

// Auth TYPES
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";